### ISSUE TITLE
Setup problem: blank page

### ISSUE THREAD

**Issue by CorvusGei** [ophian/styx#38] opened 2022-12-13 23:47 UTC
Server: Strato VPS with 6 vCores, 16 GB RAM, 500 GB SSD, Ubuntu 20.04 LTS with Plesk Obsidian, own SSL Certificate.
PHP Version 8.1.13
imagick module version | 3.7.0
DB: MariaDB 10.3.37, Port 3306
Small Problem: Setup doesn't find ImageMagick Convert
Main Problem: After opening https://www.myURL.de/index.php and entering configuration details such as the DB account and starting the setup routine, I only get a blank page. In the database, there are no tables, so I think, the setup script did nothing.

**Comment by ophian** [comment] 2022-12-14 08:07
A blank page probably means a fatal error (500) logged in your apache error / php error log file(s),
So you need to find it... to procced fixing the issue.
About not being able to find ImageMagick convert, since you use the imagick module, I think you probably don't use it or do not have it installed. Serendipity does not use imagick module (yet). So you either have to live with GD or install imagemagick 7.1+ yourself, since it is a powerful and expensive VPS.

**Comment by CorvusGei** [comment] 2022-12-14 22:26
Hi ophian, thank you for your fast answer and help. I really want to give Serendipity a Chance instead of using one of the big ones like WP.
I have installed both, Imagemagick and GD, I'll check this later, when my installation is working.
I checked my PHP logs and found an error with the database connection, I could fix it. (But really? No error thrown if the connection was refused? This perhaps should be added to Exception handling?)
I still get blank pages when opening index.php or serendipity_admin.php (after login, that worked - after that - blank page).
PHP-log says:
 child 221229 said into stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function opcache_get_status() in "mypath"/bundled-libs/voku/simple-cache/src/voku/cache/AdapterOpCache.php:36"
Thank you very much!

**Comment by ophian** [comment] 2022-12-15 09:00
> I checked my PHP logs and found an error with the database connection, I could fix it. (But really? No error thrown if the connection was refused? This perhaps should be added to Exception handling?)

Well, if you don't tell me the exact procedure and exact error to be able to reproduce, ... I can't answer this. Normally it is so that on installation we should avoid having such and better have a clear connection refused message.

> I still get blank pages when opening index.php or serendipity_admin.php (after login, that worked - after that - blank page).
> PHP-log says:
> child 221229 said into stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function opcache_get_status() in "mypath"/bundled-libs/voku/simple-cache/src/voku/cache/AdapterOpCache.php:36"

In this case it look like that Zend Opcache does not exist OR is not enabled to run. Check your phpinfo if you have “Opcode Caching” that says “Up and Running”.

The line in the code that is causing a problem is checking to see if Zend Opcache is installed and running. I suspect that it isn’t installed because it can’t find the right function to call to check the status of the Opcache.
Did you _maybe_ enable the Serendipity (experimental) cache option in "General Settings"?
If not, we must find a way to not check the voku files by something like if (! function_exists('opcache_get_status') { return false; } or so ... **but** ... 
**ähem** are YOU really using Serendipity Styx 4.0.0 ?? It is the far more developed Serendipity S9y successor living at https://ophian.github.io/ and its repository here. I ask this because my AdapterOpCache.php:36 line looks different.

**Comment by CorvusGei** [comment] 2022-12-18 23:16
Thanks for your help.
Now I'm a little bit further. I just downloaded the latest version from this repo. :-)
But I see these errors in the admin panel:
Warning: Undefined array key "template" in httpdocs/include/functions_smarty.inc.php: 987.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
Warning: Undefined array key "template" in httpdocs/include/serendipity_smarty_class.inc.php: 127.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
Warning: Undefined array key "template" in httpdocs/include/functions_smarty.inc.php: 1175.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.
Warning: Undefined array key "template" in httpdocs/include/functions_smarty.inc.php: 1217.
Administrative Login Error Warning only - not seen by visitors! Send us a note what happened where and when, please.

And it can't open the Javascript file.

**Comment by ophian** [comment] 2022-12-19 08:51
Did you start installing Styx from scratch? (_Remove the other s9y installation completely before, including the database?_)
Because $serendipity['template'] should be defined by default.

**Comment by CorvusGei** [comment] 2022-12-23 22:34
I deleted everything from the old installation and did a new installation from scratch. 
It says: Serendipity Styx 4.0.0 und PHP 8.1.13

**Comment by ophian** [comment] 2022-12-24 08:49
Hmmm.., and in which state of install process or exact backend page _when ready_ do you get this?
Since **on install** the 'template' variable should be set as a blank '' string and later on - running through the install configuration (step 3) - it would be defaulted to the 'pure' theme, which is the Standard Theme, and then written to the config database table as one of the *main* configuration items and this quite straight after the database tables were created. It would be nice if you could give me a detailled advise of where and how to get these messages, and which (unusual from default) configuration you may have set on install. It seems the written config 'template' was not set. Which database did you choose and in which flavour?

At the end, did you then try to choose a theme by yourself and submitted it? Then these messages definetely should go away, I assume, if that is the main issue.

What means you can not open the javascript file? In your Browsers page source code on click? On sudden errors they may get written to the top of the serendipity_styx.js file which then can't work and certain backend actions are not possible. So you need to check it to find out. Maybe another error occurred which somehow afterwards stopped the 'template' process...

**Comment by ophian** [comment] 2022-12-26 12:53
While this _might_ being related to your issue, I just fixed an odd regex pattern issue where my development path to the blog broke the correct access of the `serendipity(_admin).css` files for frontend and backend, w/o giving any enlightening errors.
**Solution:** Do not use `/styx/` as an URL path part for installation until next version is released.

**Comment by ophian** [comment] 2022-12-30 17:48
@CorvusGei 
Shall I close this as invalid / gone ?

**Comment by ophian** [comment] 2022-12-31 12:38
Dismiss. Feel free to re-open, when this needs a follow-up. Happy New Year.

**Closed by ophian** 2022-12-31 12:38 UTC
Labels: help wanted, invalid
